// Curated set of real, public-domain artworks with verified Wikimedia Commons
// image URLs. Tag vocabulary (periodRu/genreRu) must stay consistent with
// COLLECTORS (js/collectors.js) so matchesCriteria() in engine.js can compare them.

const ARTWORKS = [
  {
    id: 'mona-lisa',
    titleRu: 'Мона Лиза',
    artistRu: 'Леонардо да Винчи',
    year: '1503–1519',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Портрет',
    factRu: 'Картина хранится в Лувре под пуленепробиваемым стеклом и считается самой посещаемой картиной в мире.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg?width=800',
    rarity: 'epic',
    basePrice: 620000,
  },
  {
    id: 'girl-with-a-pearl-earring',
    titleRu: 'Девушка с жемчужной серёжкой',
    artistRu: 'Ян Вермеер',
    year: 'ок. 1665',
    periodRu: 'Голландское золотое время',
    genreRu: 'Портрет',
    factRu: 'Картину нередко называют «северной Моной Лизой»: личность изображённой девушки до сих пор не установлена.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/1665_Girl_with_a_Pearl_Earring.jpg?width=800',
    rarity: 'epic',
    basePrice: 560000,
  },
  {
    id: 'the-night-watch',
    titleRu: 'Ночной дозор',
    artistRu: 'Рембрандт ван Рейн',
    year: '1642',
    periodRu: 'Голландское золотое время',
    genreRu: 'Групповой портрет',
    factRu: 'Настоящее название картины — «Выступление стрелковой роты капитана Франса Баннинга Кока», а тёмный колорит она приобрела из-за потемневшего со временем лака.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/La_ronda_de_noche,_por_Rembrandt_van_Rijn.jpg?width=800',
    rarity: 'epic',
    basePrice: 540000,
  },
  {
    id: 'starry-night',
    titleRu: 'Звёздная ночь',
    artistRu: 'Винсент ван Гог',
    year: '1889',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Ван Гог написал эту картину по памяти и воображению в психиатрической лечебнице Сен-Реми, отчасти опираясь на вид из окна своей палаты.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg?width=800',
    rarity: 'epic',
    basePrice: 500000,
  },
  {
    id: 'great-wave-off-kanagawa',
    titleRu: 'Большая волна в Канагаве',
    artistRu: 'Кацусика Хокусай',
    year: 'ок. 1831',
    periodRu: 'Укиё-э',
    genreRu: 'Пейзаж',
    factRu: 'Это первая гравюра из серии «Тридцать шесть видов Фудзи»: сама гора Фудзи показана вдали, крошечной на фоне гигантской волны.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tsunami_by_hokusai_19th_century.jpg?width=800',
    rarity: 'epic',
    basePrice: 470000,
  },
  {
    id: 'the-kiss',
    titleRu: 'Поцелуй',
    artistRu: 'Густав Климт',
    year: '1907–1908',
    periodRu: 'Символизм (венский модерн)',
    genreRu: 'Жанровая сцена',
    factRu: 'Фигуры влюблённых покрыты сусальным золотом — картина принадлежит к так называемому «золотому периоду» творчества Климта.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg?width=800',
    rarity: 'epic',
    basePrice: 450000,
  },

  {
    id: 'birth-of-venus',
    titleRu: 'Рождение Венеры',
    artistRu: 'Сандро Боттичелли',
    year: '1484–1486',
    periodRu: 'Раннее Возрождение',
    genreRu: 'Мифологическая сцена',
    factRu: 'Поза Венеры повторяет композицию античной статуи «Венеры Стыдливой», известной художнику по копиям.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg?width=800',
    rarity: 'rare',
    basePrice: 210000,
  },
  {
    id: 'arnolfini-portrait',
    titleRu: 'Портрет четы Арнольфини',
    artistRu: 'Ян ван Эйк',
    year: '1434',
    periodRu: 'Северное Возрождение',
    genreRu: 'Портрет',
    factRu: 'В выпуклом зеркале на заднем плане отражаются фигуры двух людей, а рядом художник оставил подпись «Ян ван Эйк был здесь».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Van_Eyck_-_Arnolfini_Portrait.jpg?width=800',
    rarity: 'rare',
    basePrice: 195000,
  },
  {
    id: 'the-milkmaid',
    titleRu: 'Молочница',
    artistRu: 'Ян Вермеер',
    year: 'ок. 1658–1661',
    periodRu: 'Голландское золотое время',
    genreRu: 'Жанровая сцена',
    factRu: 'Для тени на переднем плане Вермеер использовал дорогой пигмент ультрамарин — необычно щедрое решение для бытовой сцены.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.png?width=800',
    rarity: 'rare',
    basePrice: 180000,
  },
  {
    id: 'rembrandt-self-portrait',
    titleRu: 'Автопортрет с двумя кругами',
    artistRu: 'Рембрандт ван Рейн',
    year: 'ок. 1665–1669',
    periodRu: 'Голландское золотое время',
    genreRu: 'Портрет',
    factRu: 'Значение двух загадочных кругов на стене за спиной художника до сих пор остаётся предметом споров искусствоведов.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rembrandt_Self-portrait_(Kenwood).jpg?width=800',
    rarity: 'rare',
    basePrice: 150000,
  },
  {
    id: 'las-meninas',
    titleRu: 'Менины',
    artistRu: 'Диего Веласкес',
    year: '1656',
    periodRu: 'Барокко',
    genreRu: 'Групповой портрет',
    factRu: 'Веласкес изобразил самого себя стоящим у мольберта — один из самых ранних примеров столь масштабной «картины в картине».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Las_Meninas,_by_Diego_Vel%C3%A1zquez,_from_Prado_in_Google_Earth.jpg?width=800',
    rarity: 'rare',
    basePrice: 195000,
  },
  {
    id: 'third-of-may-1808',
    titleRu: 'Расстрел в ночь на третье мая 1808 года',
    artistRu: 'Франсиско Гойя',
    year: '1814',
    periodRu: 'Романтизм',
    genreRu: 'Историческая сцена',
    factRu: 'Гойя написал картину спустя шесть лет после расстрела мадридских повстанцев французскими солдатами, показав войну глазами жертв, а не победителей.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_thin_black_margin.jpg?width=800',
    rarity: 'rare',
    basePrice: 160000,
  },
  {
    id: 'liberty-leading-the-people',
    titleRu: 'Свобода, ведущая народ',
    artistRu: 'Эжен Делакруа',
    year: '1830',
    periodRu: 'Романтизм',
    genreRu: 'Историческая аллегория',
    factRu: 'Женщина с флагом на переднем плане — аллегорическая Свобода, вдохновлённая образом Марианны, символа Французской республики.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg?width=800',
    rarity: 'rare',
    basePrice: 175000,
  },
  {
    id: 'impression-sunrise',
    titleRu: 'Впечатление. Восходящее солнце',
    artistRu: 'Клод Моне',
    year: '1872',
    periodRu: 'Импрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Именно от названия этой картины критик Луи Леруа насмешливо образовал слово «импрессионизм», которое художники позже сами приняли как имя течения.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Monet_-_Impression,_Sunrise.jpg?width=800',
    rarity: 'rare',
    basePrice: 220000,
  },
  {
    id: 'luncheon-of-the-boating-party',
    titleRu: 'Завтрак гребцов',
    artistRu: 'Пьер Огюст Ренуар',
    year: '1880–1881',
    periodRu: 'Импрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'На картине изображены реальные друзья Ренуара, включая его будущую жену Алину Шариго, играющую с собачкой на переднем плане.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 200000,
  },
  {
    id: 'sunflowers',
    titleRu: 'Подсолнухи',
    artistRu: 'Винсент ван Гог',
    year: '1888',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Натюрморт',
    factRu: 'Ван Гог написал серию картин с подсолнухами, чтобы украсить комнату своего друга Поля Гогена перед его приездом в Арль.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_Willem_van_Gogh_127.jpg?width=800',
    rarity: 'rare',
    basePrice: 230000,
  },

  {
    id: 'school-of-athens',
    titleRu: 'Афинская школа',
    artistRu: 'Рафаэль Санти',
    year: '1509–1511',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Философская сцена',
    factRu: 'Рафаэль придал античным философам черты своих современников: считается, что Платон на фреске написан похожим на Леонардо да Винчи.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg?width=800',
    rarity: 'common',
    basePrice: 60000,
  },
  {
    id: 'calling-of-saint-matthew',
    titleRu: 'Призвание апостола Матфея',
    artistRu: 'Караваджо',
    year: '1599–1600',
    periodRu: 'Барокко',
    genreRu: 'Религиозная сцена',
    factRu: 'Резкий контраст света и тени (кьяроскуро) направляет луч света прямо на будущего апостола, выделяя момент его призвания.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Caravaggio_%E2%80%94_The_Calling_of_Saint_Matthew.jpg?width=800',
    rarity: 'common',
    basePrice: 55000,
  },
  {
    id: 'the-swing',
    titleRu: 'Качели',
    artistRu: 'Жан-Оноре Фрагонар',
    year: 'ок. 1767',
    periodRu: 'Рококо',
    genreRu: 'Жанровая сцена',
    factRu: 'Заказчик картины пожелал, чтобы его любовница была изображена на качелях так, чтобы он мог видеть её снизу, — сюжет стал символом игривого рококо.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 50000,
  },
  {
    id: 'wanderer-above-the-sea-of-fog',
    titleRu: 'Странник над морем тумана',
    artistRu: 'Каспар Давид Фридрих',
    year: 'ок. 1818',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Фигура странника, повёрнутого спиной к зрителю, стала одним из самых узнаваемых символов немецкого романтизма.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog.jpeg?width=800',
    rarity: 'rare',
    basePrice: 120000,
  },
  {
    id: 'the-hay-wain',
    titleRu: 'Телега для сена',
    artistRu: 'Джон Констебл',
    year: '1821',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Картина изображает реальное место на реке Стур в графстве Саффолк и стала одним из символов английского сельского пейзажа.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/John_Constable_-_The_Hay_Wain_(1821).jpg?width=800',
    rarity: 'common',
    basePrice: 58000,
  },
  {
    id: 'oath-of-the-horatii',
    titleRu: 'Клятва Горациев',
    artistRu: 'Жак-Луи Давид',
    year: '1784–1785',
    periodRu: 'Неоклассицизм',
    genreRu: 'Историческая сцена',
    factRu: 'Картина прославляет гражданский долг и самопожертвование римлян и стала визуальным манифестом идеалов накануне Французской революции.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Le_Serment_des_Horaces_-_Jacques-Louis_David_-_Mus%C3%A9e_du_Louvre_Peintures_INV_3692_%3B_MR_1432.jpg?width=800',
    rarity: 'common',
    basePrice: 52000,
  },
  {
    id: 'dejeuner-sur-l-herbe',
    titleRu: 'Завтрак на траве',
    artistRu: 'Эдуард Мане',
    year: '1862–1863',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Картина вызвала скандал в парижском Салоне отверженных 1863 года из-за обнажённой женщины, спокойно сидящей рядом с одетыми по моде мужчинами.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 62000,
  },
  {
    id: 'sunday-afternoon-la-grande-jatte',
    titleRu: 'Воскресный день на острове Гранд-Жатт',
    artistRu: 'Жорж Сёра',
    year: '1884–1886',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'Картина целиком составлена из тысяч отдельных цветных точек — техника, получившая название пуантилизм, или дивизионизм.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg?width=800',
    rarity: 'common',
    basePrice: 68000,
  },

  // --- Expanded catalog (Renaissance, Baroque, Dutch Golden Age, Romanticism/
  // Neoclassicism, Impressionism/Post-Impressionism, Realism/Symbolism/Ukiyo-e) ---
  {
    id: 'last-supper',
    titleRu: 'Тайная вечеря',
    artistRu: 'Леонардо да Винчи',
    year: '1495–1498',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Религиозная сцена',
    factRu: 'Леонардо расписал стену не фреской по мокрой штукатурке, а темперой и маслом по сухой грунтовке — эксперимент дал больше свободы в деталях, но роспись начала осыпаться уже при жизни художника.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo_da_Vinci_(1452-1519)_-_The_Last_Supper_(1495-1498).jpg?width=800',
    rarity: 'epic',
    basePrice: 600000,
  },
  {
    id: 'creation-of-adam',
    titleRu: 'Сотворение Адама',
    artistRu: 'Микеланджело Буонарроти',
    year: '1508–1512',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Религиозная сцена',
    factRu: 'Фреска украшает потолок Сикстинской капеллы; в 1990 году американский врач Фрэнк Мешбергер заметил, что очертания фигуры Бога и окружающих его ангелов повторяют форму человеческого мозга в разрезе.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Michelangelo_-_Creation_of_Adam_(cropped).jpg?width=800',
    rarity: 'epic',
    basePrice: 580000,
  },
  {
    id: 'primavera',
    titleRu: 'Весна (Примавера)',
    artistRu: 'Сандро Боттичелли',
    year: 'ок. 1477–1482',
    periodRu: 'Раннее Возрождение',
    genreRu: 'Мифологическая сцена',
    factRu: 'Ботаники насчитали на картине свыше 500 растений и около 190 видов цветов, изображённых настолько точно, что учёные используют её как источник для истории флоры Тосканы.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sandro_Botticelli_-_La_Primavera_-_Google_Art_Project.jpg?width=800',
    rarity: 'epic',
    basePrice: 480000,
  },
  {
    id: 'garden-of-earthly-delights',
    titleRu: 'Сад земных наслаждений',
    artistRu: 'Иероним Босх',
    year: 'ок. 1490–1500',
    periodRu: 'Северное Возрождение',
    genreRu: 'Религиозная сцена',
    factRu: 'Об этом триптихе не сохранилось ни договора о заказе, ни подписи автора, а смысл его фантастических образов — от райского сада до ада — искусствоведы обсуждают до сих пор.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg?width=800',
    rarity: 'rare',
    basePrice: 220000,
  },
  {
    id: 'sistine-madonna',
    titleRu: 'Сикстинская Мадонна',
    artistRu: 'Рафаэль Санти',
    year: '1512–1513',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Религиозная сцена',
    factRu: 'Два задумчивых ангелочка у нижнего края холста давно живут собственной жизнью: их изображение растиражировано на открытках, обёрточной бумаге и сувенирах отдельно от всей картины.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Raphael_-_The_Sistine_Madonna_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 200000,
  },
  {
    id: 'bacchus-and-ariadne',
    titleRu: 'Вакх и Ариадна',
    artistRu: 'Тициан',
    year: '1520–1523',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Мифологическая сцена',
    factRu: 'В верхней части неба Тициан изобразил созвездие Северной Короны — по легенде, брошенную Вакхом в небо корону покинутой Ариадны.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Titian_-_Bacchus_and_Ariadne_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 190000,
  },
  {
    id: 'lady-with-an-ermine',
    titleRu: 'Дама с горностаем',
    artistRu: 'Леонардо да Винчи',
    year: 'ок. 1489–1490',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Портрет',
    factRu: 'Инфракрасное сканирование показало, что Леонардо дважды переписывал портрет Чечилии Галлерани: сперва зверька не было вовсе, затем появился маленький серый зверёк, и лишь потом — белый горностай, намекавший на прозвище миланского герцога Лодовико Сфорца.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Lady_with_an_Ermine_-_Leonardo_da_Vinci_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 170000,
  },
  {
    id: 'venus-and-mars',
    titleRu: 'Венера и Марс',
    artistRu: 'Сандро Боттичелли',
    year: 'ок. 1485',
    periodRu: 'Раннее Возрождение',
    genreRu: 'Мифологическая сцена',
    factRu: 'Гнездо ос у самого уха спящего Марса — вероятно, каламбур на фамилию Веспуччи (от итальянского vespa, «оса»), знатного флорентийского рода, который мог заказать эту картину.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Botticelli-Venus_and_Mars.jpg?width=800',
    rarity: 'rare',
    basePrice: 150000,
  },
  {
    id: 'portrait-of-a-man-in-a-red-turban',
    titleRu: 'Портрет мужчины в красном тюрбане',
    artistRu: 'Ян ван Эйк',
    year: '1433',
    periodRu: 'Северное Возрождение',
    genreRu: 'Портрет',
    factRu: 'На раме художник крупно написал свой девиз «ALS ICH KAN» («как я умею» — игра слов с его именем), а прямой взгляд модели на зрителя заставляет искусствоведов считать эту картину одним из первых европейских автопортретов.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portrait_of_a_Man_in_a_red_turban_(by_Jan_van_Eyck).jpg?width=800',
    rarity: 'rare',
    basePrice: 140000,
  },
  {
    id: 'portrait-of-erasmus',
    titleRu: 'Портрет Эразма Роттердамского',
    artistRu: 'Ганс Гольбейн Младший',
    year: '1523',
    periodRu: 'Северное Возрождение',
    genreRu: 'Портрет',
    factRu: 'Гольбейн написал несколько копий этого портрета, которые Эразм рассылал друзьям-гуманистам по всей Европе, включая Томаса Мора, — так путешествующий учёный поддерживал дружбу на расстоянии.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Holbein-erasmus.jpg?width=800',
    rarity: 'common',
    basePrice: 55000,
  },
  {
    id: 'tribute-money',
    titleRu: 'Чудо со статиром',
    artistRu: 'Мазаччо',
    year: 'ок. 1425–1427',
    periodRu: 'Раннее Возрождение',
    genreRu: 'Религиозная сцена',
    factRu: 'На одной фреске Мазаччо соединил три момента одной истории — приказ Христа, добычу монеты изо рта рыбы и уплату налога, — а сходящиеся линии портика указывают точку схода перспективы прямо на голову Христа, одно из первых столь точных перспективных построений в живописи.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Tribute_Money_Masaccio_Cappella_Brancacci.jpg?width=800',
    rarity: 'common',
    basePrice: 58000,
  },
  {
    id: 'portrait-of-innocent-x',
    titleRu: 'Портрет папы Иннокентия X',
    artistRu: 'Диего Веласкес',
    year: '1650',
    periodRu: 'Барокко',
    genreRu: 'Портрет',
    factRu: 'Увидев готовый портрет, сам папа Иннокентий X будто бы назвал его «слишком правдивым» — Веласкес не смягчил ни одной морщины стареющего понтифика.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portrait_of_Innocentius_X_by_Diego_Vel%C3%A1zquez_in_Galleria_Doria_Pamphilj_(Rome).jpg?width=800',
    rarity: 'epic',
    basePrice: 580000,
  },
  {
    id: 'judith-slaying-holofernes',
    titleRu: 'Юдифь, убивающая Олоферна',
    artistRu: 'Артемизия Джентилески',
    year: '1614–1620',
    periodRu: 'Барокко',
    genreRu: 'Религиозная сцена',
    factRu: 'Джентилески написала эту сцену через несколько лет после того, как пережила насилие и громкий судебный процесс, — многие искусствоведы видят в ярости Юдифи отражение личной истории художницы.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Judit_decapitando_a_Holofernes,_por_Artemisia_Gentileschi.jpg?width=800',
    rarity: 'epic',
    basePrice: 540000,
  },
  {
    id: 'massacre-of-the-innocents-rubens',
    titleRu: 'Избиение младенцев',
    artistRu: 'Питер Пауль Рубенс',
    year: 'ок. 1611–1612',
    periodRu: 'Барокко',
    genreRu: 'Историческая сцена',
    factRu: 'До 2001 года картину приписывали второстепенным мастерам, а в 2002 году, уже как подлинник Рубенса, она была продана на Sotheby\'s за 49,5 млн фунтов — рекордная на тот момент цена для картины старого мастера.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rubens_-_Massacre_of_the_Innocents_-_Art_Gallery_of_Ontario_2.jpg?width=800',
    rarity: 'epic',
    basePrice: 610000,
  },
  {
    id: 'rubens-isabella-brant-honeysuckle-bower',
    titleRu: 'Рубенс и Изабелла Брант в беседке из жимолости',
    artistRu: 'Питер Пауль Рубенс',
    year: 'ок. 1609–1610',
    periodRu: 'Барокко',
    genreRu: 'Групповой портрет',
    factRu: 'Рубенс написал этот двойной портрет вскоре после свадьбы с Изабеллой Брант: сплетённые руки супругов и куст жимолости над ними символизируют верность и семейное счастье.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Peter_Paul_Rubens_-_Rubens_and_Isabella_Brant_in_the_honeysuckle_bower.jpg?width=800',
    rarity: 'rare',
    basePrice: 175000,
  },
  {
    id: 'five-eldest-children-of-charles-i',
    titleRu: 'Пятеро старших детей Карла I',
    artistRu: 'Антонис ван Дейк',
    year: '1637',
    periodRu: 'Барокко',
    genreRu: 'Групповой портрет',
    factRu: 'Ван Дейк изобразил детей английского короля живыми и по-детски естественными, порвав с традицией представлять венценосных отпрысков «маленькими взрослыми».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Anthony_van_Dyck_-_Five_Eldest_Children_of_Charles_I_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 165000,
  },
  {
    id: 'self-portrait-allegory-of-painting',
    titleRu: 'Автопортрет в образе Живописи',
    artistRu: 'Артемизия Джентилески',
    year: 'ок. 1638–1639',
    periodRu: 'Барокко',
    genreRu: 'Портрет',
    factRu: 'По канону эпохи аллегория Живописи изображалась только женской фигурой — Джентилески оказалась единственной художницей своего времени, способной буквально стать этой аллегорией в собственном автопортрете.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Self-Portrait_as_the_Allegory_of_Painting_(La_Pittura)_-_Artemisia_Gentileschi.jpg?width=800',
    rarity: 'rare',
    basePrice: 150000,
  },
  {
    id: 'supper-at-emmaus-caravaggio',
    titleRu: 'Ужин в Эммаусе',
    artistRu: 'Караваджо',
    year: '1601',
    periodRu: 'Барокко',
    genreRu: 'Религиозная сцена',
    factRu: 'Караваджо написал воскресшего Христа безбородым и юным: по евангельскому рассказу апостолы не сразу узнали Спасителя, и художник буквально показал эту неузнаваемость.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/1602-3_Caravaggio,Supper_at_Emmaus_National_Gallery,_London.jpg?width=800',
    rarity: 'rare',
    basePrice: 200000,
  },
  {
    id: 'saint-serapion',
    titleRu: 'Святой Серапион',
    artistRu: 'Франсиско де Сурбаран',
    year: '1628',
    periodRu: 'Барокко',
    genreRu: 'Религиозная сцена',
    factRu: 'Картина создавалась для траурного зала монастыря мерседариев в Севилье: Сурбаран почти полностью убрал кровь и раны, сосредоточившись на белой драпировке одеяния и тишине смерти.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/San_Serapio,_por_Francisco_de_Zurbar%C3%A1n.jpg?width=800',
    rarity: 'rare',
    basePrice: 140000,
  },
  {
    id: 'rape-of-the-sabine-women-poussin',
    titleRu: 'Похищение сабинянок',
    artistRu: 'Никола Пуссен',
    year: '1637–1638',
    periodRu: 'Барокко',
    genreRu: 'Историческая сцена',
    factRu: 'Это уже вторая версия сюжета у Пуссена — более раннюю, написанную несколькими годами ранее в Риме, сегодня можно увидеть в Метрополитен-музее в Нью-Йорке.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Poussin_RapeSabineLouvre.jpg?width=800',
    rarity: 'rare',
    basePrice: 155000,
  },
  {
    id: 'apollo-and-marsyas-ribera',
    titleRu: 'Аполлон и Марсий',
    artistRu: 'Хусепе де Рибера',
    year: '1637',
    periodRu: 'Барокко',
    genreRu: 'Мифологическая сцена',
    factRu: 'Рибера, всю жизнь работавший в Неаполе под испанским владычеством, получил там прозвище «Ло Спаньолетто» («Маленький испанец») — эта сцена наказания сатира Марсия считается одним из самых натуралистичных воплощений мифа в живописи.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jos%C3%A9_de_Ribera_-_Apollo_Flaying_Marsyas_-_WGA19374.jpg?width=800',
    rarity: 'common',
    basePrice: 62000,
  },
  {
    id: 'atalanta-and-hippomenes-reni',
    titleRu: 'Аталанта и Гиппомен',
    artistRu: 'Гвидо Рени',
    year: 'ок. 1620–1625',
    periodRu: 'Барокко',
    genreRu: 'Мифологическая сцена',
    factRu: 'Сюжет взят из «Метаморфоз» Овидия: хитрый Гиппомен обгоняет непобедимую бегунью Аталанту, на бегу бросая ей под ноги золотые яблоки, которые она не может не поднять.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Guido_Reni_-_Atalanta_and_Hippomenes_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 56000,
  },
  {
    id: 'the-anatomy-lesson-of-dr-nicolaes-tulp',
    titleRu: 'Урок анатомии доктора Тульпа',
    artistRu: 'Рембрандт ван Рейн',
    year: '1632',
    periodRu: 'Голландское золотое время',
    genreRu: 'Групповой портрет',
    factRu: 'Труп на столе — казнённый преступник Арис Кинт, повешенный в тот же день за уличный грабёж; хирурги гильдии заказали картину для своего зала в амстердамской Ваге. Рентген холста показал, что кисть руки трупа была переписана — сперва Рембрандт честно изобразил обрубок, оставшийся после ампутации.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg?width=800',
    rarity: 'epic',
    basePrice: 590000,
  },
  {
    id: 'the-jewish-bride',
    titleRu: 'Еврейская невеста',
    artistRu: 'Рембрандт ван Рейн',
    year: 'ок. 1665–1669',
    periodRu: 'Голландское золотое время',
    genreRu: 'Портрет',
    factRu: 'Название картине в 1825 году придумал коллекционер ван дер Хооп, решив, что перед нами отец, дарящий дочери свадебное украшение; кем на самом деле изображена пара, искусствоведы спорят до сих пор. Ван Гог признавался, что отдал бы десять лет жизни за две недели перед этим полотном с куском сухого хлеба.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rembrandt_Harmensz._van_Rijn_-_Het_Joodse_bruidje.jpg?width=800',
    rarity: 'epic',
    basePrice: 540000,
  },
  {
    id: 'the-laughing-cavalier',
    titleRu: 'Смеющийся кавалер',
    artistRu: 'Франс Хальс',
    year: '1624',
    periodRu: 'Голландское золотое время',
    genreRu: 'Портрет',
    factRu: 'Модель на портрете вовсе не смеётся и, возможно, никогда не была кавалером — звучное название придумала лишь викторианская публика Лондона в 1870-х годах. Имя изображённого мужчины неизвестно: надпись на картине сохранила только его возраст — 26 лет — и дату написания.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cavalier_soldier_Hals-1624x.jpg?width=800',
    rarity: 'epic',
    basePrice: 470000,
  },
  {
    id: 'the-feast-of-saint-nicholas',
    titleRu: 'Праздник святого Николая',
    artistRu: 'Ян Стен',
    year: 'ок. 1665–1668',
    periodRu: 'Голландское золотое время',
    genreRu: 'Жанровая сцена',
    factRu: 'Девочка на переднем плане получила целую корзину подарков от Синтерклааса, а её незадачливый брат слева со слезами разглядывает лишь пучок розог. Фамилия художника подарила нидерландцам крылатое выражение «дом Яна Стена» — синоним весёлого домашнего беспорядка.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jan_Steen_-_The_Feast_of_St._Nicholas_-_WGA21722.jpg?width=800',
    rarity: 'rare',
    basePrice: 175000,
  },
  {
    id: 'the-courtyard-of-a-house-in-delft',
    titleRu: 'Дворик дома в Делфте',
    artistRu: 'Питер де Хох',
    year: '1658',
    periodRu: 'Голландское золотое время',
    genreRu: 'Жанровая сцена',
    factRu: 'Каменная плита с латинской надписью 1614 года над проходом — не выдумка художника: она была снята с портала снесённого монастыря и вмонтирована в стену соседнего двора, который де Хох и запечатлел. Свою подпись «P.D.H. / A 1658» художник поместил прямо на арке слева.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pieter_de_Hooch_-_The_Courtyard_of_a_House_in_Delft.jpg?width=800',
    rarity: 'rare',
    basePrice: 190000,
  },
  {
    id: 'the-gallant-conversation',
    titleRu: 'Галантная беседа',
    artistRu: 'Герард тер Борх',
    year: 'ок. 1654',
    periodRu: 'Голландское золотое время',
    genreRu: 'Жанровая сцена',
    factRu: 'Долгое время картину называли «Отцовским наставлением», полагая, что мужчина отчитывает дочь, — но при внимательном рассмотрении выяснилось, что он держит в пальцах монету, а сцена изображает совсем не отцовскую заботу. Тер Борха современники ценили прежде всего за поразительно достоверную передачу блеска атласных тканей.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gerard_ter_Borch_(II)_019.jpg?width=800',
    rarity: 'rare',
    basePrice: 135000,
  },
  {
    id: 'still-life-with-a-nautilus-cup',
    titleRu: 'Натюрморт с чашей наутилуса и китайской чашей',
    artistRu: 'Виллем Кальф',
    year: '1662',
    periodRu: 'Голландское золотое время',
    genreRu: 'Натюрморт',
    factRu: 'Раковину создала природа, ремесленник превратил её в драгоценный кубок, а Кальф — в предмет живописи: эта подписанная и датированная работа служит опорной точкой для датировки всего его творчества. Персидский ковёр и лимон, очищенный по спирали, — фирменные приёмы «прунк»-натюрмортов художника.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Still_Life_with_Chinese_Bowl_and_Nautilus_1662_Willem_Kalf.jpg?width=800',
    rarity: 'rare',
    basePrice: 205000,
  },
  {
    id: 'the-proposition',
    titleRu: 'Предложение',
    artistRu: 'Юдит Лейстер',
    year: '1631',
    periodRu: 'Голландское золотое время',
    genreRu: 'Жанровая сцена',
    factRu: 'Редкий для голландской живописи взгляд с женской стороны: мужчина навязчиво предлагает девушке монеты, а она демонстративно не отрывается от шитья. Когда директор Маурицхёйса купил картину в 1892 году, автор ещё не был установлен — саму Лейстер к тому времени почти забыли.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Judith_Leyster_-_The_Proposition_-_WGA12958.jpg?width=800',
    rarity: 'rare',
    basePrice: 145000,
  },
  {
    id: 'the-windmill-at-wijk-bij-duurstede',
    titleRu: 'Мельница у Вейк-бей-Дёйрстеде',
    artistRu: 'Якоб ван Рёйсдал',
    year: 'ок. 1670',
    periodRu: 'Голландское золотое время',
    genreRu: 'Пейзаж',
    factRu: 'Та самая мельница давно не существует, но само здание, снятое снизу словно памятник на фоне драматического неба, стало почти символом голландского пейзажа. С 1885 года картина висит в Галерее почёта амстердамского Рейксмузеум.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/De_molen_bij_Wijk_bij_Duurstede,_SK-C-211.jpg?width=800',
    rarity: 'common',
    basePrice: 58000,
  },
  {
    id: 'the-goldfinch',
    titleRu: 'Щегол',
    artistRu: 'Карел Фабрициус',
    year: '1654',
    periodRu: 'Голландское золотое время',
    genreRu: 'Натюрморт',
    factRu: 'В том же 1654 году взрыв порохового склада — так называемый «Делфтский гром» — разрушил четверть города и убил самого художника, уничтожив почти всё его наследие: сохранилось не более дюжины полотен. Картина дала название роману Донны Тартт «Щегол», получившему Пулитцеровскую премию.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Carel_Fabritius_-_The_Goldfinch_-_605_-_Mauritshuis.jpg?width=800',
    rarity: 'common',
    basePrice: 65000,
  },
  {
    id: 'regentesses-of-the-old-mens-almshouse',
    titleRu: 'Регентши приюта для престарелых',
    artistRu: 'Франс Хальс',
    year: '1664',
    periodRu: 'Голландское золотое время',
    genreRu: 'Групповой портрет',
    factRu: 'Хальс писал эту картину в 81 год, практически нищим и вынужденным всю жизнь распродавать имущество за долги, — отсюда непривычно грубая и размашистая манера письма. Полотно создано для харлемской богадельни, здание которой сегодня занимает Музей Франса Хальса.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Frans_Hals_-_De_regentessen_van_het_oudemannenhuis.jpg?width=800',
    rarity: 'rare',
    basePrice: 160000,
  },
  {
    id: 'the-fighting-temeraire',
    titleRu: 'Последний рейс корабля «Отважный»',
    artistRu: 'Уильям Тёрнер',
    year: '1839',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Тёрнер называл эту картину своей любимой и наотрез отказывался её продавать; в 2005 году она была признана «величайшей картиной Британии» по результатам опроса BBC Radio 4.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg?width=800',
    rarity: 'rare',
    basePrice: 175000,
  },
  {
    id: 'the-raft-of-the-medusa',
    titleRu: 'Плот «Медузы»',
    artistRu: 'Теодор Жерико',
    year: '1818–1819',
    periodRu: 'Романтизм',
    genreRu: 'Историческая сцена',
    factRu: 'Сюжет основан на реальном крушении фрегата «Медуза» в 1816 году: ради анатомической точности Жерико изучал тела в морге и беседовал с выжившими, которым пришлось прибегнуть к каннибализму.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Raft_of_the_Medusa_-_Louvre.jpg?width=800',
    rarity: 'epic',
    basePrice: 580000,
  },
  {
    id: 'saturn-devouring-his-son',
    titleRu: 'Сатурн, поглощающий своего сына',
    artistRu: 'Франсиско Гойя',
    year: 'ок. 1819–1823',
    periodRu: 'Романтизм',
    genreRu: 'Мифологическая сцена',
    factRu: 'Картина входит в серию из 14 «Чёрных картин», которые Гойя написал прямо на стенах своего дома и никогда не предназначал для публичного показа.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Francisco_de_Goya,_Saturno_devorando_a_su_hijo_(1819-1823).jpg?width=800',
    rarity: 'rare',
    basePrice: 165000,
  },
  {
    id: 'the-sea-of-ice',
    titleRu: 'Море льда',
    artistRu: 'Каспар Давид Фридрих',
    year: '1823–1824',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Разбитый корабль среди нагромождённых льдин отсылает к неудачным арктическим экспедициям Уильяма Парри; современники картину не приняли, и она оставалась непроданной до самой смерти художника в 1840 году.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Caspar_David_Friedrich_-_The_Sea_of_Ice_-_WGA8270.jpg?width=800',
    rarity: 'rare',
    basePrice: 140000,
  },
  {
    id: 'the-last-day-of-pompeii',
    titleRu: 'Последний день Помпеи',
    artistRu: 'Карл Брюллов',
    year: '1830–1833',
    periodRu: 'Романтизм',
    genreRu: 'Историческая сцена',
    factRu: 'Полотно вдохновило Пушкина на неоконченное стихотворение, а в левом верхнем углу художник изобразил самого себя, убегающим от извержения с ящиком красок на голове.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Briullov,_The_Last_Day_of_Pompeii_(1827%E2%80%931833).jpg?width=800',
    rarity: 'rare',
    basePrice: 190000,
  },
  {
    id: 'the-ninth-wave',
    titleRu: 'Девятый вал',
    artistRu: 'Иван Айвазовский',
    year: '1850',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Название отсылает к старинному поверью моряков: девятый вал в шторме считался самым большим и опасным, после которого буря должна была стихнуть.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aivazovsky,_Ivan_-_The_Ninth_Wave.jpg?width=800',
    rarity: 'common',
    basePrice: 65000,
  },
  {
    id: 'pinkie-sarah-barrett-moulton',
    titleRu: 'Пинки (Портрет Сары Баррет Мултон)',
    artistRu: 'Томас Лоуренс',
    year: '1794',
    periodRu: 'Романтизм',
    genreRu: 'Портрет',
    factRu: 'Портрет одиннадцатилетней Сары Баррет Мултон впервые показали на выставке Королевской академии, открывшейся на следующий день после её похорон: девочка умерла от чахотки, не дожив до окончания работы над картиной.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Lawrence_-_Sarah_Barrett_Moulton,_Pinkie.jpg?width=800',
    rarity: 'common',
    basePrice: 54000,
  },
  {
    id: 'the-death-of-marat',
    titleRu: 'Смерть Марата',
    artistRu: 'Жак-Луи Давид',
    year: '1793',
    periodRu: 'Неоклассицизм',
    genreRu: 'Историческая сцена',
    factRu: 'Давид написал картину сразу после убийства своего друга Марата, придав сцене вид светской пьеты, а на деревянном постаменте оставил надпись «À Marat, David».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jacques-Louis_David_-_Marat_assassinated_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 155000,
  },
  {
    id: 'bonaparte-crossing-the-alps',
    titleRu: 'Бонапарт на перевале Сен-Бернар',
    artistRu: 'Жак-Луи Давид',
    year: '1802–1803',
    periodRu: 'Неоклассицизм',
    genreRu: 'Портрет',
    factRu: 'В реальности Наполеон пересекал перевал на муле, в сером плаще и через несколько дней после своей армии, но по его личному пожеланию Давид изобразил его на вздыбленном коне — художник написал пять версий этого портрета.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jacques-Louis_David_-_Napoleon_Crossing_the_Alps_-_Kunsthistorisches_Museum.jpg?width=800',
    rarity: 'epic',
    basePrice: 480000,
  },
  {
    id: 'napoleon-on-his-imperial-throne',
    titleRu: 'Наполеон I на императорском троне',
    artistRu: 'Жан-Огюст-Доминик Энгр',
    year: '1806',
    periodRu: 'Неоклассицизм',
    genreRu: 'Портрет',
    factRu: 'Хиератическая поза Наполеона на троне восходит к античным изображениям Зевса и средневековым образам Христа во славе; современники нашли картину слишком архаичной и «готической».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ingres,_Napoleon_on_his_Imperial_throne.jpg?width=800',
    rarity: 'rare',
    basePrice: 145000,
  },
  {
    id: 'cornelia-mother-of-the-gracchi',
    titleRu: 'Корнелия, мать Гракхов, указывающая на своих детей как на свои сокровища',
    artistRu: 'Анжелика Кауфман',
    year: '1785',
    periodRu: 'Неоклассицизм',
    genreRu: 'Историческая аллегория',
    factRu: 'Кауфман была одной из двух женщин среди 36 основателей Королевской академии художеств в Лондоне в 1768 году; сюжет картины — рассказ о римлянке Корнелии, показавшей гостье вместо драгоценностей своих сыновей.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kauffmann_Cornelia_mater_Gracchorum.jpg?width=800',
    rarity: 'common',
    basePrice: 51000,
  },
  {
    id: 'water-lilies',
    titleRu: 'Кувшинки',
    artistRu: 'Клод Моне',
    year: '1906',
    periodRu: 'Импрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Моне писал кувшинки в своём саду в Живерни: за последние три десятилетия жизни он создал около 250 полотен с этим мотивом, постепенно убирая с холста линию горизонта и превращая пруд в бескрайнее поле цвета и отражений.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Claude_Monet_-_Water_Lilies_-_1906,_Ryerson.jpg?width=800',
    rarity: 'epic',
    basePrice: 480000,
  },
  {
    id: 'the-ballet-class',
    titleRu: 'Балетный класс',
    artistRu: 'Эдгар Дега',
    year: '1873–1876',
    periodRu: 'Импрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'Пожилого руководителя урока Дега писал с реального человека — бывшего танцовщика и балетмейстера Жюля Перро, который в молодости выступал в Парижской опере и в Петербурге.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Edgar_Degas_-_The_Ballet_Class_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 180000,
  },
  {
    id: 'bal-du-moulin-de-la-galette',
    titleRu: 'Бал в Мулен де ла Галетт',
    artistRu: 'Пьер Огюст Ренуар',
    year: '1876',
    periodRu: 'Импрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'Ренуар писал картину прямо на месте — в саду танцевального кабаре на Монмартре, а моделями стали его друзья-художники и парижские модистки, включая похожих друг на друга сестёр Жанну и Эстель.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bal_du_moulin_de_la_Galette,_by_Pierre-Auguste_Renoir,_Mus%C3%A9e_d%27Orsay,_Paris_(36322968145).jpg?width=800',
    rarity: 'epic',
    basePrice: 520000,
  },
  {
    id: 'boulevard-montmartre-at-night',
    titleRu: 'Бульвар Монмартр ночью',
    artistRu: 'Камиль Писсарро',
    year: '1897',
    periodRu: 'Импрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Это единственная ночная картина в серии из четырнадцати видов бульвара Монмартр, которые Писсарро писал из окна гостиничного номера в разное время суток, года и погоды.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Camille_Pissarro_-_Boulevard_Montmartre_at_Night_-_c_1897_-_National_Gallery_UK.jpg?width=800',
    rarity: 'rare',
    basePrice: 150000,
  },
  {
    id: 'the-cradle',
    titleRu: 'Колыбель',
    artistRu: 'Берта Моризо',
    year: '1872',
    periodRu: 'Импрессионизм',
    genreRu: 'Портрет',
    factRu: 'Моризо показала «Колыбель» на первой выставке импрессионистов в 1874 году, став единственной женщиной среди участников; на картине — её сестра Эдма, наблюдающая за спящей дочерью Бланш.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Berthe_Morisot_-_The_Cradle_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 140000,
  },
  {
    id: 'little-girl-in-a-blue-armchair',
    titleRu: 'Маленькая девочка в синем кресле',
    artistRu: 'Мэри Кассат',
    year: '1878',
    periodRu: 'Импрессионизм',
    genreRu: 'Портрет',
    factRu: 'Композицию картины Кассат помог доработать Дега: инфракрасные снимки Национальной галереи искусств подтвердили, что именно он написал часть пола и придал пространству между креслами более смелый, асимметричный ракурс.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mary_Cassatt_-_Little_Girl_in_a_Blue_Armchair_-_NGA_1983.1.18.jpg?width=800',
    rarity: 'common',
    basePrice: 58000,
  },
  {
    id: 'the-basket-of-apples',
    titleRu: 'Корзина с яблоками',
    artistRu: 'Поль Сезанн',
    year: 'ок. 1893',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Натюрморт',
    factRu: 'Левый и правый края стола на картине не сходятся в одну линию — рентген показал, что этот «сбой» перспективы Сезанн задумал изначально, стремясь передать не фотографическую точность, а само движение взгляда.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Paul_C%C3%A9zanne_-_The_Basket_of_Apples_-_1926.252_-_Art_Institute_of_Chicago.jpg?width=800',
    rarity: 'rare',
    basePrice: 170000,
  },
  {
    id: 'tahitian-women-on-the-beach',
    titleRu: 'Таитянские женщины на пляже',
    artistRu: 'Поль Гоген',
    year: '1891',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'Гоген написал эту картину уже летом 1891 года, вскоре после прибытия на Таити, куда он уехал в поисках «первозданной» жизни, далёкой от европейской цивилизации и салонного искусства Парижа.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Gauguin_056.jpg?width=800',
    rarity: 'rare',
    basePrice: 190000,
  },
  {
    id: 'cafe-terrace-at-night',
    titleRu: 'Терраса кафе ночью',
    artistRu: 'Винсент ван Гог',
    year: '1888',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Ван Гог писал эту картину прямо на площади Форума в Арле при свете газовых фонарей и, по собственным словам, обошёлся без чёрной краски вовсе; это первая его работа со звёздным небом — на год раньше «Звёздной ночи».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_van_Gogh_(1853-1890)_Caf%C3%A9terras_bij_nacht_(place_du_Forum)_Kr%C3%B6ller-M%C3%BCller_Museum_Otterlo_23-8-2016_13-35-40.JPG?width=800',
    rarity: 'epic',
    basePrice: 550000,
  },
  {
    id: 'at-the-moulin-rouge',
    titleRu: 'В Мулен Руж',
    artistRu: 'Анри де Тулуз-Лотрек',
    year: '1892–1895',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'Сам художник изобразил себя крошечной фигурой на заднем плане рядом с высоким кузеном — доктором Тапье де Селейраном, а справа на переднем плане с загадочным зеленоватым лицом — танцовщица Мэй Мильтон.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Henri_de_Toulouse-Lautrec,_At_the_Moulin_Rouge.jpg?width=800',
    rarity: 'rare',
    basePrice: 210000,
  },
  {
    id: 'bathers-at-asnieres',
    titleRu: 'Купальщики в Аньере',
    artistRu: 'Жорж Сёра',
    year: '1884',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Сёра писал картину незадолго до «Воскресного дня на острове Гранд-Жатт»: фигуры купальщиков он тщательно продумывал отдельно на этюдах, а затем собрал их в цельную композицию на берегу Сены напротив заводских труб Клиши.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Baigneurs_a_Asnieres.jpg?width=800',
    rarity: 'common',
    basePrice: 64000,
  },
  {
    id: 'barge-haulers-on-the-volga',
    titleRu: 'Бурлаки на Волге',
    artistRu: 'Илья Репин',
    year: '1870–1873',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Прежде чем писать картину, Репин несколько лет ездил на Волгу и рисовал с натуры настоящих бурлаков; готовое полотно купил великий князь Владимир Александрович, брат будущего императора.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ilya_Repin_-_Barge_Haulers_on_the_Volga_-_Google_Art_Project.jpg?width=800',
    rarity: 'epic',
    basePrice: 470000,
  },
  {
    id: 'portrait-of-adele-bloch-bauer-i',
    titleRu: 'Портрет Адели Блох-Бауэр I',
    artistRu: 'Густав Климт',
    year: '1907',
    periodRu: 'Символизм (венский модерн)',
    genreRu: 'Портрет',
    factRu: 'Картину, которую называют «Женщина в золоте», нацисты отобрали у семьи Блох-Бауэр в 1938 году; после долгой судебной тяжбы она была возвращена наследнице и в 2006 году продана за 135 миллионов долларов.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gustav_Klimt,_1907,_Adele_Bloch-Bauer_I,_Neue_Galerie_New_York.jpg?width=800',
    rarity: 'epic',
    basePrice: 580000,
  },
  {
    id: 'the-gleaners',
    titleRu: 'Собирательницы колосьев',
    artistRu: 'Жан-Франсуа Милле',
    year: '1857',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Картина изображает крестьянок, подбирающих на поле оставшиеся после жатвы колоски, — консервативная парижская публика восприняла этот сюжет как дерзкое возвышение бедноты до масштаба большой живописи.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 150000,
  },
  {
    id: 'a-bar-at-the-folies-bergere',
    titleRu: 'Бар в Фоли-Бержер',
    artistRu: 'Эдуард Мане',
    year: '1882',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Отражение в зеркале за спиной барменши Сюзон не совпадает с тем, что должно быть видно по законам оптики, — эту загадку перспективы искусствоведы обсуждают уже больше века.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Edouard_Manet,_A_Bar_at_the_Folies-Berg%C3%A8re.jpg?width=800',
    rarity: 'rare',
    basePrice: 190000,
  },
  {
    id: 'the-sin',
    titleRu: 'Грех',
    artistRu: 'Франц фон Штук',
    year: '1893',
    periodRu: 'Символизм (венский модерн)',
    genreRu: 'Историческая аллегория',
    factRu: 'Картина имела такой успех на выставке Мюнхенского Сецессиона 1893 года, что сразу сделала Штука знаменитым; всего художник написал около десятка авторских вариантов этого сюжета.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Franz_von_Stuck_-_Die_S%C3%BCnde_1893.jpg?width=800',
    rarity: 'rare',
    basePrice: 135000,
  },
  {
    id: 'portrait-of-wally-neuzil',
    titleRu: 'Портрет Валли Нойциль',
    artistRu: 'Эгон Шиле',
    year: '1912',
    periodRu: 'Символизм (венский модерн)',
    genreRu: 'Портрет',
    factRu: 'Валли Нойциль была близкой спутницей и музой Шиле; сам портрет много лет находился в центре громкого судебного спора о нацистских трофейных ценностях в США, который завершился лишь в 2010 году выплатой 19 миллионов долларов.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Egon_Schiele_-_Portrait_of_Wally_Neuzil_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 125000,
  },
  {
    id: 'red-fuji',
    titleRu: 'Красная Фудзи (Южный ветер, ясный день)',
    artistRu: 'Кацусика Хокусай',
    year: 'ок. 1830–1832',
    periodRu: 'Укиё-э',
    genreRu: 'Пейзаж',
    factRu: 'В отличие от «Большой волны» из той же серии, здесь Хокусай обошёлся всего тремя красками и не изобразил ни одного человека — всё внимание отдано горе Фудзи в лучах рассвета.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Katsushika_Hokusai_-_Fine_Wind,_Clear_Morning_(Gaif%C5%AB_kaisei)_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 160000,
  },
  {
    id: 'sudden-shower-over-shin-ohashi-bridge',
    titleRu: 'Внезапный ливень над мостом Син-Охаси',
    artistRu: 'Утагава Хиросигэ',
    year: '1857',
    periodRu: 'Укиё-э',
    genreRu: 'Пейзаж',
    factRu: 'Ливень передан десятками тонких параллельных линий, вырезанных на печатной доске; этот приём в 1887 году скопировал маслом Винсент ван Гог в своей картине «Мост в дождь».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hiroshige,_Sudden_shower_over_Shin-%C5%8Chashi_bridge_and_Atake,_1857.jpg?width=800',
    rarity: 'rare',
    basePrice: 170000,
  },
  {
    id: 'a-burial-at-ornans',
    titleRu: 'Похороны в Орнане',
    artistRu: 'Гюстав Курбе',
    year: '1849–1850',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Полотно длиной более шести метров — масштаб, который тогда полагался лишь историческим или религиозным сюжетам, — изображает обычные похороны в родном городке художника и вызвало скандал на Салоне 1850–1851 годов.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gustave_Courbet_-_A_Burial_at_Ornans_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 65000,
  },
  {
    id: 'the-gulf-stream',
    titleRu: 'Гольфстрим',
    artistRu: 'Уинслоу Хомер',
    year: '1899',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Публику взволновала неясная судьба моряка на обломках лодки среди акул; раздражённый вопросами о его судьбе, Хомер саркастично написал своему торговцу картинами, что тот скоро «будет спасён, вернётся к друзьям и дому и заживёт долго и счастливо».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Winslow_Homer_-_The_Gulf_Stream_(1899).jpg?width=800',
    rarity: 'common',
    basePrice: 58000,
  },
  {
    id: 'three-beauties-of-the-present-day',
    titleRu: 'Три красавицы наших дней',
    artistRu: 'Китагава Утамаро',
    year: 'ок. 1793',
    periodRu: 'Укиё-э',
    genreRu: 'Жанровая сцена',
    factRu: 'На гравюре изображены три реальные знаменитости эпохи Эдо — гейша Томимото Тоёхина и две чайные подавальщицы, — которых Утамаро наделил тонкими индивидуальными чертами, необычными для портретной условности укиё-э.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitagawa_Utamaro_-_Toji_san_bijin_(Three_Beauties_of_the_Present_Day)From_Bijin-ga_(Pictures_of_Beautiful_Women),_published_by_Tsutaya_Juzaburo_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 54000,
  },
];

ARTWORKS.forEach((artwork) => {
  artwork.imageUrl = `assets/art/${artwork.id}.webp`;
});
