// Curated set of real, public-domain artworks with verified Wikimedia Commons
// image URLs. Tag vocabulary (periodRu/genreRu) must stay consistent with
// COLLECTORS (js/collectors.js) so matchesCriteria() in engine.js can compare them.

const ARTWORKS = [
  {
    id: 'mona-lisa',
    titleRu: 'Мона Лиза',
    artistRu: 'Леонардо да Винчи',
    year: '1503–1519',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Портрет',
    factRu: 'Картина хранится в Лувре под пуленепробиваемым стеклом и считается самой посещаемой картиной в мире.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg?width=800',
    rarity: 'epic',
    basePrice: 620000,
  },
  {
    id: 'girl-with-a-pearl-earring',
    titleRu: 'Девушка с жемчужной серёжкой',
    artistRu: 'Ян Вермеер',
    year: 'ок. 1665',
    periodRu: 'Голландское золотое время',
    genreRu: 'Портрет',
    factRu: 'Картину нередко называют «северной Моной Лизой»: личность изображённой девушки до сих пор не установлена.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/1665_Girl_with_a_Pearl_Earring.jpg?width=800',
    rarity: 'epic',
    basePrice: 560000,
  },
  {
    id: 'the-night-watch',
    titleRu: 'Ночной дозор',
    artistRu: 'Рембрандт ван Рейн',
    year: '1642',
    periodRu: 'Голландское золотое время',
    genreRu: 'Групповой портрет',
    factRu: 'Настоящее название картины — «Выступление стрелковой роты капитана Франса Баннинга Кока», а тёмный колорит она приобрела из-за потемневшего со временем лака.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/La_ronda_de_noche,_por_Rembrandt_van_Rijn.jpg?width=800',
    rarity: 'epic',
    basePrice: 540000,
  },
  {
    id: 'starry-night',
    titleRu: 'Звёздная ночь',
    artistRu: 'Винсент ван Гог',
    year: '1889',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Ван Гог написал эту картину по памяти и воображению в психиатрической лечебнице Сен-Реми, отчасти опираясь на вид из окна своей палаты.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg?width=800',
    rarity: 'epic',
    basePrice: 500000,
  },
  {
    id: 'great-wave-off-kanagawa',
    titleRu: 'Большая волна в Канагаве',
    artistRu: 'Кацусика Хокусай',
    year: 'ок. 1831',
    periodRu: 'Укиё-э',
    genreRu: 'Пейзаж',
    factRu: 'Это первая гравюра из серии «Тридцать шесть видов Фудзи»: сама гора Фудзи показана вдали, крошечной на фоне гигантской волны.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tsunami_by_hokusai_19th_century.jpg?width=800',
    rarity: 'epic',
    basePrice: 470000,
  },
  {
    id: 'the-kiss',
    titleRu: 'Поцелуй',
    artistRu: 'Густав Климт',
    year: '1907–1908',
    periodRu: 'Символизм (венский модерн)',
    genreRu: 'Жанровая сцена',
    factRu: 'Фигуры влюблённых покрыты сусальным золотом — картина принадлежит к так называемому «золотому периоду» творчества Климта.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg?width=800',
    rarity: 'epic',
    basePrice: 450000,
  },

  {
    id: 'birth-of-venus',
    titleRu: 'Рождение Венеры',
    artistRu: 'Сандро Боттичелли',
    year: '1484–1486',
    periodRu: 'Раннее Возрождение',
    genreRu: 'Мифологическая сцена',
    factRu: 'Поза Венеры повторяет композицию античной статуи «Венеры Стыдливой», известной художнику по копиям.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg?width=800',
    rarity: 'rare',
    basePrice: 210000,
  },
  {
    id: 'arnolfini-portrait',
    titleRu: 'Портрет четы Арнольфини',
    artistRu: 'Ян ван Эйк',
    year: '1434',
    periodRu: 'Северное Возрождение',
    genreRu: 'Портрет',
    factRu: 'В выпуклом зеркале на заднем плане отражаются фигуры двух людей, а рядом художник оставил подпись «Ян ван Эйк был здесь».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Van_Eyck_-_Arnolfini_Portrait.jpg?width=800',
    rarity: 'rare',
    basePrice: 195000,
  },
  {
    id: 'the-milkmaid',
    titleRu: 'Молочница',
    artistRu: 'Ян Вермеер',
    year: 'ок. 1658–1661',
    periodRu: 'Голландское золотое время',
    genreRu: 'Жанровая сцена',
    factRu: 'Для тени на переднем плане Вермеер использовал дорогой пигмент ультрамарин — необычно щедрое решение для бытовой сцены.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.png?width=800',
    rarity: 'rare',
    basePrice: 180000,
  },
  {
    id: 'rembrandt-self-portrait',
    titleRu: 'Автопортрет с двумя кругами',
    artistRu: 'Рембрандт ван Рейн',
    year: 'ок. 1665–1669',
    periodRu: 'Голландское золотое время',
    genreRu: 'Портрет',
    factRu: 'Значение двух загадочных кругов на стене за спиной художника до сих пор остаётся предметом споров искусствоведов.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rembrandt_Self-portrait_(Kenwood).jpg?width=800',
    rarity: 'rare',
    basePrice: 150000,
  },
  {
    id: 'las-meninas',
    titleRu: 'Менины',
    artistRu: 'Диего Веласкес',
    year: '1656',
    periodRu: 'Барокко',
    genreRu: 'Групповой портрет',
    factRu: 'Веласкес изобразил самого себя стоящим у мольберта — один из самых ранних примеров столь масштабной «картины в картине».',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Las_Meninas,_by_Diego_Vel%C3%A1zquez,_from_Prado_in_Google_Earth.jpg?width=800',
    rarity: 'rare',
    basePrice: 195000,
  },
  {
    id: 'third-of-may-1808',
    titleRu: 'Расстрел в ночь на третье мая 1808 года',
    artistRu: 'Франсиско Гойя',
    year: '1814',
    periodRu: 'Романтизм',
    genreRu: 'Историческая сцена',
    factRu: 'Гойя написал картину спустя шесть лет после расстрела мадридских повстанцев французскими солдатами, показав войну глазами жертв, а не победителей.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_thin_black_margin.jpg?width=800',
    rarity: 'rare',
    basePrice: 160000,
  },
  {
    id: 'liberty-leading-the-people',
    titleRu: 'Свобода, ведущая народ',
    artistRu: 'Эжен Делакруа',
    year: '1830',
    periodRu: 'Романтизм',
    genreRu: 'Историческая аллегория',
    factRu: 'Женщина с флагом на переднем плане — аллегорическая Свобода, вдохновлённая образом Марианны, символа Французской республики.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg?width=800',
    rarity: 'rare',
    basePrice: 175000,
  },
  {
    id: 'impression-sunrise',
    titleRu: 'Впечатление. Восходящее солнце',
    artistRu: 'Клод Моне',
    year: '1872',
    periodRu: 'Импрессионизм',
    genreRu: 'Пейзаж',
    factRu: 'Именно от названия этой картины критик Луи Леруа насмешливо образовал слово «импрессионизм», которое художники позже сами приняли как имя течения.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Monet_-_Impression,_Sunrise.jpg?width=800',
    rarity: 'rare',
    basePrice: 220000,
  },
  {
    id: 'luncheon-of-the-boating-party',
    titleRu: 'Завтрак гребцов',
    artistRu: 'Пьер Огюст Ренуар',
    year: '1880–1881',
    periodRu: 'Импрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'На картине изображены реальные друзья Ренуара, включая его будущую жену Алину Шариго, играющую с собачкой на переднем плане.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg?width=800',
    rarity: 'rare',
    basePrice: 200000,
  },
  {
    id: 'sunflowers',
    titleRu: 'Подсолнухи',
    artistRu: 'Винсент ван Гог',
    year: '1888',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Натюрморт',
    factRu: 'Ван Гог написал серию картин с подсолнухами, чтобы украсить комнату своего друга Поля Гогена перед его приездом в Арль.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_Willem_van_Gogh_127.jpg?width=800',
    rarity: 'rare',
    basePrice: 230000,
  },

  {
    id: 'school-of-athens',
    titleRu: 'Афинская школа',
    artistRu: 'Рафаэль Санти',
    year: '1509–1511',
    periodRu: 'Высокое Возрождение',
    genreRu: 'Философская сцена',
    factRu: 'Рафаэль придал античным философам черты своих современников: считается, что Платон на фреске написан похожим на Леонардо да Винчи.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg?width=800',
    rarity: 'common',
    basePrice: 60000,
  },
  {
    id: 'calling-of-saint-matthew',
    titleRu: 'Призвание апостола Матфея',
    artistRu: 'Караваджо',
    year: '1599–1600',
    periodRu: 'Барокко',
    genreRu: 'Религиозная сцена',
    factRu: 'Резкий контраст света и тени (кьяроскуро) направляет луч света прямо на будущего апостола, выделяя момент его призвания.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Caravaggio_%E2%80%94_The_Calling_of_Saint_Matthew.jpg?width=800',
    rarity: 'common',
    basePrice: 55000,
  },
  {
    id: 'the-swing',
    titleRu: 'Качели',
    artistRu: 'Жан-Оноре Фрагонар',
    year: 'ок. 1767',
    periodRu: 'Рококо',
    genreRu: 'Жанровая сцена',
    factRu: 'Заказчик картины пожелал, чтобы его любовница была изображена на качелях так, чтобы он мог видеть её снизу, — сюжет стал символом игривого рококо.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 50000,
  },
  {
    id: 'wanderer-above-the-sea-of-fog',
    titleRu: 'Странник над морем тумана',
    artistRu: 'Каспар Давид Фридрих',
    year: 'ок. 1818',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Фигура странника, повёрнутого спиной к зрителю, стала одним из самых узнаваемых символов немецкого романтизма.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog.jpeg?width=800',
    rarity: 'common',
    basePrice: 65000,
  },
  {
    id: 'the-hay-wain',
    titleRu: 'Телега для сена',
    artistRu: 'Джон Констебл',
    year: '1821',
    periodRu: 'Романтизм',
    genreRu: 'Пейзаж',
    factRu: 'Картина изображает реальное место на реке Стур в графстве Саффолк и стала одним из символов английского сельского пейзажа.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/John_Constable_-_The_Hay_Wain_(1821).jpg?width=800',
    rarity: 'common',
    basePrice: 58000,
  },
  {
    id: 'oath-of-the-horatii',
    titleRu: 'Клятва Горациев',
    artistRu: 'Жак-Луи Давид',
    year: '1784–1785',
    periodRu: 'Неоклассицизм',
    genreRu: 'Историческая сцена',
    factRu: 'Картина прославляет гражданский долг и самопожертвование римлян и стала визуальным манифестом идеалов накануне Французской революции.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Le_Serment_des_Horaces_-_Jacques-Louis_David_-_Mus%C3%A9e_du_Louvre_Peintures_INV_3692_%3B_MR_1432.jpg?width=800',
    rarity: 'common',
    basePrice: 52000,
  },
  {
    id: 'dejeuner-sur-l-herbe',
    titleRu: 'Завтрак на траве',
    artistRu: 'Эдуард Мане',
    year: '1862–1863',
    periodRu: 'Реализм',
    genreRu: 'Жанровая сцена',
    factRu: 'Картина вызвала скандал в парижском Салоне отверженных 1863 года из-за обнажённой женщины, спокойно сидящей рядом с одетыми по моде мужчинами.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg?width=800',
    rarity: 'common',
    basePrice: 62000,
  },
  {
    id: 'sunday-afternoon-la-grande-jatte',
    titleRu: 'Воскресный день на острове Гранд-Жатт',
    artistRu: 'Жорж Сёра',
    year: '1884–1886',
    periodRu: 'Постимпрессионизм',
    genreRu: 'Жанровая сцена',
    factRu: 'Картина целиком составлена из тысяч отдельных цветных точек — техника, получившая название пуантилизм, или дивизионизм.',
    imageSource: 'https://commons.wikimedia.org/wiki/Special:FilePath/A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg?width=800',
    rarity: 'common',
    basePrice: 68000,
  },
];

ARTWORKS.forEach((artwork) => {
  artwork.imageUrl = `assets/art/${artwork.id}.webp`;
});
